# my-devops-project/kubernetes/postgresql.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Be om 5 GB lagringsplass. Juster etter behov.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest # Bruker det offisielle PostgreSQL bildet
        ports:
        - containerPort: 5432
          name: pg-port
        env:
        # Viktig: I et EKTE PRODUKSJONSMILJØ vil du IKKE hardkode passord her.
        # Bruk Kubernetes Secrets!
        - name: POSTGRES_DB
          value: "employeesdb" # Databasenavn du brukte tidligere
        - name: POSTGRES_USER
          value: "appuser"     # Brukernavn du brukte tidligere
        - name: POSTGRES_PASSWORD
          value: "mydevpassword" # Passord du brukte tidligere. ENDRE DETTE I PRODUKSJON!
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # Standard datamappe for PostgreSQL
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: pg-port
  type: ClusterIP # Standard type, kun tilgjengelig innenfor klyngen

  # FOR TESTING (IKKE I PRODUKSJON): NodePort eksponering
  # type: NodePort
  # nodePort: 30087 # Eksponerer på denne porten på noden
